apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: vergeops/k8s-rvstore-ui:1.0
        ports:
        - name: ui-port
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: ui-port
        readinessProbe:
          httpGet:
            path: /
            port: ui-port
          periodSeconds: 10
          successThreshold: 2
          failureThreshold: 1
        startupProbe:
          httpGet:
            path: /
            port: ui-port
          periodSeconds: 10
          failureThreshold: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
    spec:
      volumes:
      - name: products-volume
        configMap:
          name: products-config   
      containers:
      - name: rvstore-product-api
        image: vergeops/k8s-rvstore-product-api:1.0
        ports:
        - name: product-port
          containerPort: 9001
        volumeMounts:
        - name: products-volume
          mountPath: /data/products
        env:
        - name: PRODUCT_FILE_LOCATION
          value: /data/products
        livenessProbe:
          httpGet:
            path: /products/
            port: product-port
        readinessProbe:
          httpGet:
            path: /products/
            port: product-port
          periodSeconds: 10
          successThreshold: 2
          failureThreshold: 1
        startupProbe:
          httpGet:
            path: /products/
            port: product-port
          periodSeconds: 10
          failureThreshold: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
      - name: rvstore-auth-api
        image: vergeops/k8s-rvstore-auth-api:1.0
        ports:
        - name: auth-port
          containerPort: 9003
        livenessProbe:
          httpGet:
            path: /auth/login
            port: auth-port
        readinessProbe:
          httpGet:
            path: /auth/login
            port: auth-port
          periodSeconds: 10
          successThreshold: 2
          failureThreshold: 1
        startupProbe:
          httpGet:
            path: /auth/login
            port: auth-port
          periodSeconds: 10
          failureThreshold: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
      - name: rvstore-order-api
        image: vergeops/k8s-rvstore-order-api:1.0
        envFrom:
        - configMapRef:
            name: workload-config
        ports:
        - name: order-port
          containerPort: 9002
        livenessProbe:
          httpGet:
            path: /orders
            port: order-port
        readinessProbe:
          httpGet:
            path: /orders
            port: order-port
          periodSeconds: 10
          successThreshold: 2
          failureThreshold: 1
        startupProbe:
          httpGet:
            path: /orders
            port: order-port
          periodSeconds: 10
          failureThreshold: 5

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-simulator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-simulator
  template:
    metadata:
      labels:
        app: order-simulator
    spec:
      containers:
      - name: rvstore-order-simulator
        image: vergeops/k8s-rvstore-order-simulator:1.0
        envFrom:
        - configMapRef:
            name: workload-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: rvstore-api-gateway
        image: vergeops/k8s-rvstore-api-gateway:1.0
        ports:
        - name: gw-port
          containerPort: 9000
        envFrom:
        - configMapRef:
            name: workload-config
        livenessProbe:
          httpGet:
            path: /health
            port: gw-port
        readinessProbe:
          httpGet:
            path: /health
            port: gw-port
          periodSeconds: 10
          successThreshold: 2
          failureThreshold: 1
        startupProbe:
          httpGet:
            path: /health
            port: gw-port
          periodSeconds: 10
          failureThreshold: 5
